### PR TITLE
Introduced NLog.AspNetCore.SignalR

### PR DESCRIPTION
**Pull request by snakefoot**
Added sibling-package to NLog.SignalR, that depends on `Microsoft.AspNetCore.SignalR.Client` (no longer depends on newtonsoft json or jquery)

### CODE REVIEW

**Comment by snakefoot** [comment]
Could also consider creating a whole new repository

**Comment by snakefoot** [comment]
@toddmeinershagen Any preferred direction from this pull-request?

**Comment by toddmeinershagen** [comment]
@snakefoot - when I download your fork, the sample application doesn't run and the tests are not working.  Do they work on your local?

**Comment by snakefoot** [comment]
They worked 1 year ago, but seems that my Visual Studio 2022 Test-discovery not working for the old `NLog.SignalR.IntegrationTests`-project. But the new `NLog.AspNetCore.SignalR.Tests`-project can run, but there is a change in the connection-recovery-state, so after `StartAsync`-completion then connection-state remains "Connecting" instead of "Connected".

**Comment by snakefoot** [comment]
@toddmeinershagen Have updated dependencies, and now unit-test and example project is working on VS2022.

**Comment by toddmeinershagen** [comment]
I have updated things to .net 4.8 on my local.  What are your thoughts on upgrading?  I think that anything less than 4.6.2 is not even secure or supported at this point.

**Comment by snakefoot** [comment]
The net45 is only an target API, then actual runtime installed on operating system is usually updated and secure.

There can be an issue with net45-API will at some point not be recognised by the latest build tools. I think net461 or net462 is good for the nuget package. You can update the example projects to NET48 if you like.



Sent from my Galaxy



-------- Original message --------
From: Todd Meinershagen ***@***.***>
Date: 19/07/2023 05:07 (GMT+01:00)
To: "toddmeinershagen/NLog.SignalR" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [toddmeinershagen/NLog.SignalR] Introduced NLog.AspNetCore.SignalR (PR #20)


I have updated things to .net 4.8 on my local. What are your thoughts on upgrading? I think that anything less than 4.6.2 is not even secure or supported at this point.

**Pull request merged**
