### PR TITLE
NLog with NetStandard support and VS2017 csproj

### LINKED ISSUE #3: Adding support for .Net Core 1.0.1+
Hello there!
I am having issues using a custom target to log events to a SignalR Hub. I tried working around your code but  I didnt have any luck. Any help would be much appreciated. The following are more details on this issue.

`
2017-01-08 17:47:16.2061 Error Error in Parsing Configuration File. Exception: NLog.NLogConfigurationException: Exception occurred when loading configuration from C:\OSI_TFS\Mini\Web API\Exl.WebApi.Aspen\Exl.WebApi.Aspen\nlog.config
System.ArgumentException: Target cannot be found: 'SignalR'
   at NLog.Config.Factory2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)`

And in my Nlog.config
`<extensions><add assembly="SignalR.App"/>
    </extensions>
    <variable name="appName" value="App" />
     <target xsi:type="SignalR" name="signalr" layout="${appName}::${message} ${onexception:${exception:format=type,message,method:maxInnerExceptionLevel=5:innerExceptionSeparator=:separator=/}}"/>`

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #3

To build nuget-package. Right-click the project in Vs2017 and choose "Pack" or run this command:

`dotnet pack .\src\NLog.SignalR --configuration Release --include-symbols`

### CODE REVIEW

**Comment by snakefoot** [comment]
@toddmeinershagen Not sure how to update the appveyor-build to use `image: Visual Studio 2017`

**Comment by toddmeinershagen** [comment]
@snakefoot I went ahead and updated the build to use Visual Studio 2017 (it is a drop down in the Environment tab.  After doing that, we are now getting an error with the reference to NLog 4.0.1.  I guess we may need to upgrade the NLog to a dotnet core version of NLog.  

Is this targeting 2.0??

**Comment by snakefoot** [comment]
@toddmeinershagen I can build the entire solution locally with this command:

`msbuild /t:restore,rebuild "src\NLog.SignalR.sln" /verbosity:minimal /p:configuration=Release`

I can generate the nuget package with this command:

`dotnet pack .\src\NLog.SignalR --configuration Release --include-symbols`

Not sure how to update the appveyor-build-script to handle this.

**Comment by toddmeinershagen** [comment]
@snakefoot I created an Appveyor build that ran the build command you provided and everything compiled properly.  I noticed that you are getting rid of the nuspec file and placing info at the csproj file.  

Why do we require an assembly attribute as a Guid?  (Not as familiar with releasing to nuget with dotnet core now.)

**Comment by toddmeinershagen** [comment]
Also @snakefoot it looks like you were setting the new version to 5.0.0.  Is that necessary since the last version was 2.0.0?  Just wondering if we should just bump up to the next major version to indicate a semantic breaking change at 3.0.0 instead.

**Comment by snakefoot** [comment]
> Why do we require an assembly attribute as a Guid?

It was there from the beginning, so I just left it there. Think it works together with `[assembly: ComVisible(false)]`

**Comment by snakefoot** [comment]
> you were setting the new version to 5.0.0. Is that necessary?

I just bumped the existing major version:

```
-[assembly: AssemblyVersion("4.0.1")]
-[assembly: AssemblyFileVersion("4.0.1")]

Think it matches the current nuget-package: https://www.nuget.org/packages/NLog.SignalR/4.0.1
```

**Comment by toddmeinershagen** [comment]
@snakefoot Oh - you're right.  The latest version published is 4.0.1.  I was seeing a version attribute in the src/NLog.SignalR/NLog.SignalR.csproj file that was 5.0.0.  

If this is not a breaking change for existing clients and just allows new dotnet core users to leverage it in a new way then the 4.1.0 might be the right way to go. 

Thanks for your pull request.  I will merge shortly.

**Comment by toddmeinershagen** [comment]
@snakefoot I have pushed the new version (4.1.0) to nuget.org.  Let me know if you have any issues with it.

Thanks for your help again!

Sent from Mail for Windows 10

**Pull request merged**
